version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: react-spring-app-db-1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      app_net: {}

  backend:
    build:
      context: spring-backend
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      app_net: {}
    expose:
      - "${BACKEND_PORT}"
    depends_on:
      - db

  frontend:
    build:
      context: react-frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      app_net: {}

  nginx-proxy:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    env_file:
        - .env
    ports:
        - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
        app_net: {}

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
